### PR TITLE
Feature/web load transactions

### PR DESCRIPTION
**Pull request by MichalMichanski**
Loading transactions into Web, as of this commit without ID (which makes edit and create a problemorino) due to some arcane errors, thats for another commit

### CODE REVIEW

**Comment by MichalMichanski** [comment]
ID now gets added, as of now just a fat ass rand int, since our id is a int we cant really use guid, eventually i think we should be moving that way tho.

I still want to refactor this, one interesting issue ive noticed - it's possible to perform actions on a transaction accessed through the transactions tab, but not when accessing a list of users transaction within users, any ideas ?

**Review by MariuszMalec — COMMENTED** [review]
I think randy loaded list of Transaction shouldn't have type "ALL" only "outcome" and "Income" is needed.

**Review by MariuszMalec — COMMENTED** [review]
to fix problem with IDy add in file UserTransactions.cshtml

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>

**Review by MariuszMalec — COMMENTED** [review]
random list generate not correct type with category , it's mean I noticed that outcome is salary?

**Review by MariuszMalec — APPROVED** [review]

**Pull request merged**
